image:  desenvolvimento.azurecr.io/prepaid/account
version: ${version}
enviroments:
  values: 
    APP_PROFILE: hmlg
    CACHE_ENABLED: true
    CACHE_ENTITIES_TENANT: #{ACCOUNT_VNEXT_HMLE_CACHE_ENTITIES_TENANT}#
    DATABASE_CONNECTIONURI: #{ACCOUNT_VNEXT_HMLE_DATABASE_CONNECTIONURI}#
    DATABASE_KEEPALIVE: 60
    DATABASE_POOLISSUERS_CONNMAXLIFETIME: 10
    DATABASE_POOLISSUERS_MAXIDLECONNS: 2
    DATABASE_POOLISSUERS_MAXOPENCONNS: 2
    DATABASE_POOLPRINCIPAL_CONNMAXLIFETIME: 10
    DATABASE_POOLPRINCIPAL_MAXIDLECONNS: 1
    DATABASE_POOLPRINCIPAL_MAXOPENCONNS: 2
    DATABASE_SHOWSQL: false
    DATABASE_TIMEZONE: UTC
    KAFKA_BROKERS: #{ACCOUNT_VNEXT_HMLE_KAFKA_BROKERS}#
    KAFKA_DEBUG: true
    KAFKA_ENABLED: true
    KAFKA_PRODUCER_ACK: one
    LOG_LEVEL: info
    RABBIT_DATAHUB_DIAL: #{ACCOUNT_VNEXT_HMLE_RABBIT_DATAHUB_DIAL}#
    RABBIT_DATAHUB_VIRTUALHOST: #{ACCOUNT_VNEXT_HMLE_RABBIT_DATAHUB_VIRTUALHOST}#
    REDIS_DB: 8
    REDIS_TLS: true
    REDIS_URL: #{ACCOUNT_VNEXT_HMLE_REDIS_URL}#
    SERVER_PORT: 8080
    SPLUNK_ENABLED: true
    SPLUNK_SKIPTLS: true
    SPLUNK_SOURCE: #{ACCOUNT_VNEXT_HMLE_SPLUNK_SOURCE}#
    SPLUNK_URL: #{ACCOUNT_VNEXT_HMLE_SPLUNK_URL}#
    SWAGGER_IP: #{ACCOUNT_VNEXT_HMLE_SWAGGER_IP}#
    SWAGGER_PORT: 80

  secrets:
    DATABASE_PASSWORD: #{ACCOUNT_VNEXT_HMLE_DATABASE_PASSWORD}#
    DATABASE_USER: #{ACCOUNT_VNEXT_HMLE_DATABASE_USER}#
    REDIS_PASSWORD: #{ACCOUNT_VNEXT_HMLE_REDIS_PASSWORD}#
    SPLUNK_TOKEN: #{ACCOUNT_VNEXT_HMLE_SPLUNK_TOKEN}#

resources:
  limits:
    cpu: 4
    memory: 512Mi
  requests: 
    cpu: 100m
    memory: 256Mi

registry:
  servers:
    - name: desenvolvimento
      server: desenvolvimento.azurecr.io
      username: desenvolvimento
      password: #{VNEXT_HMLE_REGISTRY_PASSWORD}#


istio:
  enabled: true 