service:
  type: LoadBalancer
  annotations: 
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"    

rabbitmq:
  service:
    annotations: 
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"    