controller:
  service:
    internal:
      loadBalancerIP: ${loadBalancerIP}
      annotations:
        cloud.google.com/load-balancer-type: Internal
        networking.gke.io/internal-load-balancer-allow-global-access: "true"