resources:
  repositories:
    - repository: templates
      type: git
      ref: refs/heads/master
      name: Conductor IaC/Azure Pipeline

trigger: none

variables:
  - group: kubernetes-base
  - group: hmlg-gke-devops-interno
#   - group: csp-cipher-1

stages:
  # - template: terraform/pipeline.yaml@templates
  #   parameters:
  #     directory: ./terraform/$(CLOUD)/kubernetes/$(PROJECT_NAME)
  #     jobEnvironment: "$(JOB_ENVIRONMENT)"
  #     environment: "$(ENVIRONMENT)"
  #     stateName: "Infrastructure"

  - template: terraform/pipeline.yaml@templates
    parameters:
      directory: ./terraform/application/$(PROJECT_NAME)
      jobEnvironment: "$(JOB_ENVIRONMENT)"
      environment: "$(ENVIRONMENT)"
      stateName: "Application"

      beforeExecute: |
        CERT_KEY_PATH="$(certificate_key.secureFilePath)"
        CERT_PEM_PATH="$(certificate_pem.secureFilePath)"
        CERT_KEY_VALUE=$(cat $CERT_KEY_PATH | base64)
        CERT_PEM_VALUE=$(cat $CERT_PEM_PATH | base64)      

      arguments: 
        - '-var=cert_value="${CERT_PEM_VALUE}"'
        - '-var=cert_key_value="${CERT_KEY_VALUE}"'

      preSteps:
        - task: DownloadSecureFile@1
          name: certificate_key
          displayName: 'Download Certificate Key'
          inputs:
            secureFile: 'devcdt.key'

        - task: DownloadSecureFile@1
          name: certificate_pem
          displayName: 'Download Certificate'
          inputs:
            secureFile: 'devcdt.pem'                  