image: ${image}
version: ${version}

enviroments:
  values:
    SERVER_FORWARD-HEADERS-STRATEGY : NONE
    SPRING_REDIS_HOST: redis.redis-default
    
service:
  type: LoadBalancer
  annotations:
    cloud.google.com/load-balancer-type: Internal
    networking.gke.io/internal-load-balancer-allow-global-access: "true"   

registry:
  - name: conductorcr
    server: conductorcr.azurecr.io
    username: conductorcr
    password: #{REGISTRY_PASSWORD}#


livenessProbe:
  httpGet:
    path: /v1/api/monitor/health/liveness
    port: http
  initialDelaySeconds: 60
  failureThreshold: 30
  periodSeconds: 10

autoScale:
  enabled: true 
  minReplicas: 1

redis:
  enabled: false
  name: redis
  namespace:
    create: false