image: desenvolvimento.azurecr.io/prepaid/product
version: ${version}
enviroments:
  values:
    APP_PROFILE: hmlg
    CACHE_ENABLED: true 
    CACHE_ENTITIES_TENANT: false 
    CACHE_TYPE: redis
    DATABASE_CONNECTIONURI: #{PRODUCT_VNEXT_HMLE_DATABASE_CONNECTIONURI}#
    DATABASE_MIGRATIONPRINCIPAL_MAXIMUMPOOLSIZE: 2
    DATABASE_MIGRATIONPRINCIPAL_MINIMUMIDLE: 1
    DATABASE_SHOWSQL: false 
    DATABASE_TIMEZONE: UTC
    LOG_LEVEL: info
    SPLUNK_ENABLED: true
    SPLUNK_SKIPTLS: true
    SPLUNK_SOURCE: product
    SPLUNK_URL: #{PRODUCT_VNEXT_HMLE_SPLUNK_URL}#
    SWAGGER_IP: #{PRODUCT_VNEXT_HMLE_SWAGGER_IP}#
    SWAGGER_PORT: #{PRODUCT_VNEXT_HMLE_SWAGGER_PORT}#

  secrets:
    DATABASE_PASSWORD: #{PRODUCT_VNEXT_HMLE_DATABASE_PASSWORD}#
    DATABASE_USER: #{PRODUCT_VNEXT_HMLE_DATABASE_USER}#
    SPLUNK_TOKEN: #{PRODUCT_VNEXT_HMLE_SPLUNK_TOKEN}#

startupProbe:
  periodSeconds: 60
  
resources:
  limits:
    cpu: 4
    memory: 521Mi
  requests: 
    cpu: 100m
    memory: 256Mi

registry:
  servers:
    - name: desenvolvimento
      server: desenvolvimento.azurecr.io
      username: desenvolvimento
      password: #{VNEXT_HMLE_REGISTRY_PASSWORD}#

namespace:
  create: false
  labels: {}
  annotations: {}  
istio:
  enabled: true 
  
