api:
  replicas: 1
  imagePullSecret: conductorcr
  image: conductorcr.azurecr.io/api-prod/jarvis
  version: 0.36.0

  nodeSelector:
    jarvis: "true"
  
  enviroments:
    # non sensitive variables
    values:
      JARVIS_API_CONNECTIONS_SOCKETCLIENT_TIMEOUTCONNECTION: '100'
      JARVIS_API_CONNECTIONS_SOCKETCLIENT_TIMEOUTTRANSACTIONAL: '300'
      JARVIS_CORE_API_RELOADISSUERS: '30000'
      JARVIS_CORE_OUTPUT_WORKFLOWTRANSACIONAISDB: DmodelSTUB
      JARVIS_CORE_OUTPUT_WORKFLOWTRANSACIONAISRB: DmodelSTUB
      JARVIS_CORE_PIER_ACCOUNT-BLOCK-PATH: /contas/{accountId}/bloquear?id_status={status}
      JARVIS_CORE_PIER_ACCOUNT-UNBLOCK-PATH: /contas/{accountId}/reativar
      JARVIS_CORE_PIER_UNBLOCK-PATH: /cartoes/{panId}/desbloquear
      JARVIS_CORE_SFTP_HOST: 10.50.140.6
      SPRING_PROFILES_ACTIVE: prod
    # sensitive variables
    secrets:
      JARVIS_CORE_SFTP_PASSWORD: #{JARVIS_CORE_SFTP_PASSWORD}#
      JARVIS_API_SECURITY_SECRET: #{JARVIS_API_SECURITY_SECRET}# 

  resources:
    limits:
      cpu: 600m
      memory: 2.5Gi
    requests:
      cpu: 200m
      memory: 1.5Gi

  service:
    type: LoadBalancer
  
  autoScale:
    minReplicas: 3
    maxReplicas: 6
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75     
      

authorize:
  replicas: 1
  imagePullSecret: conductorcr
  image: conductorcr.azurecr.io/authorize-prod/jarvis
  version: 0.36.0

  nodeSelector:
    jarvis: "true"
  
  enviroments:
    # non sensitive variables
    values: 
      JARVIS_AUTHORIZE_CONNECTIONS_HEALTHCHECKSERVER_MAXCONNECTIONS: '5'
      JARVIS_AUTHORIZE_CONNECTIONS_SOCKETCLIENT_CONNECTIONSTIMEOUT: '1000'
      JARVIS_AUTHORIZE_CONNECTIONS_SOCKETCLIENT_LISTENERIP: 10.50.140.29
      JARVIS_AUTHORIZE_CONNECTIONS_SOCKETCLIENT_MAXCONNECTIONS: '0'
      JARVIS_AUTHORIZE_CONNECTIONS_SOCKETCLIENT_MAXIDLECONNECTIONS: '0'
      JARVIS_AUTHORIZE_CONNECTIONS_SOCKETCLIENT_MINIDLECONNECTIONS: '0'
      JARVIS_AUTHORIZE_CONNECTIONS_SOCKETCLIENT_WORKDIR: certificado/ConductorFalcon2.jks
      JARVIS_AUTHORIZE_CONNECTIONS_SOCKETSERVERRBTRAN_NAME: socket-server-autorizador-retail-banking
      JARVIS_AUTHORIZE_CONNECTIONS_TRANSACTIONAL_COREPOOLSIZE: '400'
      JARVIS_AUTHORIZE_CONNECTIONS_TRANSACTIONAL_MAXIMUMPOOLSIZE: '450'
      JARVIS_AUTHORIZE_TIMEOUT: '1400'
      JARVIS_CORE_API_RELOADISSUERS: '900000'
      JARVIS_CORE_OUTPUT_WORKFLOWTRANSACIONAISDB: DmodelSTUB
      JARVIS_CORE_PIER_ACCOUNT-BLOCK-PATH: /contas/{accountId}/bloquear?id_status={status}
      JARVIS_CORE_PIER_ACCOUNT-UNBLOCK-PATH: /contas/{accountId}/reativar
      JARVIS_CORE_SFTP_HOST: 10.50.140.6
      SPRING_PROFILES_ACTIVE: prod
    # sensitive variables
    secrets:
      JARVIS_AUTHORIZE_API_TOKEN: #{JARVIS_AUTHORIZE_API_TOKEN}#
      JARVIS_AUTHORIZE_CONNECTIONS_SOCKETCLIENT_PASSWORD: #{JARVIS_AUTHORIZE_CONNECTIONS_SOCKETCLIENT_PASSWORD}#
      JARVIS_CORE_SFTP_PASSWORD: #{JARVIS_CORE_SFTP_PASSWORD}# 

  resources:
    limits:
      cpu: 700m
      memory: 2.5Gi
    requests:
      cpu: 200m
      memory: 1Gi

  service:
    type: LoadBalancer
  
  autoScale:
    minReplicas: 3
    maxReplicas: 6
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75

cam:
  replicas: 3
  imagePullSecret: conductorcr
  image: conductorcr.azurecr.io/cam-prod/jarvis
  version: 0.36.0

  nodeSelector:
    jarvis: "true"
  
  enviroments:
    # non sensitive variables
    values: 
      JARVIS_CAM_CONNECTIONS_SOCKETCLIENT_CONNECTIONS: '0'
      JARVIS_CAM_CONNECTIONS_SOCKETCLIENT_LISTENERIP: 10.50.140.6
      JARVIS_CAM_CONNECTIONS_SOCKETCLIENT_WORKDIR: certificado/ConductorFalcon2.jks
      JARVIS_CAM_LOCKI_URL: http://10.50.22.31:9090/api/
      JARVIS_CAM_PIEROPERATIONS_ACCOUNT_BLOCK_CODE: '1'
      JARVIS_CAM_PIEROPERATIONS_ACCOUNT_BLOCK_TYPEOPERATION: '1'
      JARVIS_CAM_PIEROPERATIONS_ACCOUNT_REMOVEBLOCK_CODE: '0'
      JARVIS_CAM_PIEROPERATIONS_ACCOUNT_REMOVEBLOCK_TYPEOPERATION: '0'
      JARVIS_CAM_PIEROPERATIONS_ENABLED: 'true'
      JARVIS_CAM_PIEROPERATIONS_PAN_DEFINITIVEBLOCK_CODE: '201'
      JARVIS_CAM_PIEROPERATIONS_PAN_DEFINITIVEBLOCK_TYPEOPERATION: '2'
      JARVIS_CAM_PIEROPERATIONS_PAN_REMOVEBLOCK_CODE: '1'
      JARVIS_CAM_PIEROPERATIONS_PAN_REMOVEBLOCK_TYPEOPERATION: '0'
      JARVIS_CAM_PIEROPERATIONS_PAN_TEMPORARYBLOCK_CODE: '200'
      JARVIS_CAM_PIEROPERATIONS_PAN_TEMPORARYBLOCK_TYPEOPERATION: '1'
      JARVIS_CAM_RELOADCAMCONNECTIONS: '7200000'
      JARVIS_CAM_RELOADTOKENS: '1800000'
      JARVIS_CORE_API_RELOADISSUERS: '600000'
      JARVIS_CORE_OUTPUT_WORKFLOWTRANSACIONAISDB: DmodelSTUB
      JARVIS_CORE_PIER_ACCOUNT-BLOCK-PATH: /contas/{accountId}/bloquear?id_status={status}
      JARVIS_CORE_PIER_ACCOUNT-UNBLOCK-PATH: /contas/{accountId}/reativar
      JARVIS_CORE_PIER_BLOCK-PATH: /cartoes/{panId}/bloquear?id_status={status}&observacao={observation}
      JARVIS_CORE_PIER_CARD-PATH: /cartoes?numeroCartao={pan}
      JARVIS_CORE_PIER_UNBLOCK-PATH: /cartoes/{panId}/desbloquear
      JARVIS_CORE_SFTP_HOST: 10.50.140.6
      SPRING_PROFILES_ACTIVE: prod
    # sensitive variables
    secrets:
      JARVIS_CAM_CONNECTIONS_SOCKETCLIENT_PASSWORD: #{JARVIS_CAM_CONNECTIONS_SOCKETCLIENT_PASSWORD}#
      JARVIS_CORE_SFTP_PASSWORD: #{JARVIS_CORE_SFTP_PASSWORD}# 

  resources: 
    limits:
      cpu: 600m
      memory: 2Gi
    requests:
      cpu: 300m
      memory: 1.5Gi

batch:
  replicas: 3
  imagePullSecret: conductorcr
  image: conductorcr.azurecr.io/batch-prod/jarvis
  version: 0.36.0

  nodeSelector:
    jarvis: "true"
  
  enviroments:
    # non sensitive variables
    values:
      JARVIS_BATCH_SQLSERVER_USER: jarvis_Kafka
      JARVIS_BATCH_API_ENABLEFAILOVER: 'true'
      JARVIS_BATCH_CIPHER_ENABLEBINCHAVE: 'true'
      JARVIS_BATCH_CIPHER_TIMEOUT: '10000'
      JARVIS_BATCH_OUTPUT_UPLOADTIME: '3600000'
      JARVIS_BATCH_SCHEDULER_TYPEORDER: CIS,BIS,AIS,PIS
      JARVIS_BATCH_WORKFLOWCADASTRAIS: DRBTRAN
      JARVIS_BATCH_WORKFLOWCADASTRAISPIS: DBC14AA
      JARVIS_CORE_API_RELOADISSUERS: '600000'
      JARVIS_CORE_OUTPUT_WORKFLOWTRANSACIONAISDB: DmodelSTUB
      JARVIS_CORE_OUTPUT_WORKFLOWTRANSACIONAISRB: DmodelSTUB
      JARVIS_CORE_PIER_ACCOUNT-BLOCK-PATH: /contas/{accountId}/bloquear?id_status={status}
      JARVIS_CORE_PIER_ACCOUNT-UNBLOCK-PATH: /contas/{accountId}/reativar
      SPRING_PROFILES_ACTIVE: prod
    # sensitive variables
    secrets:
      JARVIS_BATCH_API_TOKEN: #{JARVIS_BATCH_API_TOKEN}# 
      JARVIS_BATCH_SQLSERVER_HOST: #{JARVIS_BATCH_SQLSERVER_HOST}#
      JARVIS_BATCH_SQLSERVER_PASSWORD: #{JARVIS_BATCH_SQLSERVER_PASSWORD}#

  resources:
    limits:
      cpu: 900m
      memory: 3Gi
    requests:
      cpu: 400m
      memory: 2Gi

management:
  replicas: 1
  imagePullSecret: conductorcr
  image: conductorcr.azurecr.io/management-prod/jarvis
  version: 0.36.0

  nodeSelector:
    jarvis: "true"
  
  service:
    type: LoadBalancer

  enviroments:
    # non sensitive variables
    values: 
      JARVIS_MANAGEMENT_CONNECTOR-CLASS_USER: jarvis_Kafka
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: '8080'
      ALERT_ENABLE: 'false'
      CONNECT_URL: http://localhost:8000/#/
      JARVIS_MANAGEMENT_PUBLIC_URL: http://management:8080
      MONITOR_ELASTICSEARCH_INDEX: management_center_monitor
    # sensitive variables
    secrets:
      JARVIS_MANAGEMENT_CONNECTOR-CLASS_PASSWORD: #{JARVIS_MANAGEMENT_CONNECTOR-CLASS_PASSWORD}#
      JARVIS_MANAGEMENT_CONNECTOR-CLASS_URL: #{JARVIS_MANAGEMENT_CONNECTOR-CLASS_URL}#
      SPRING_DATA_MONGODB_URI: #{SPRING_DATA_MONGODB_URI}#
      SPRING_MAIL_USERNAME: #{SPRING_MAIL_USERNAME}#
      SPRING_SECURITY_USER_NAME: #{SPRING_SECURITY_USER_NAME}#
      SPRING_SECURITY_USER_PASSWORD: #{SPRING_SECURITY_USER_PASSWORD}#
      JARVIS_MANAGEMENT_API_ACCESS-TOKEN: #{JARVIS_MANAGEMENT_API_ACCESS-TOKEN}#
      JARVIS_MANAGEMENT_HASHTOKEN: #{JARVIS_MANAGEMENT_HASHTOKEN}#  
  resources:
    limits:
      cpu: 900m
      memory: 3Gi
    requests:
      cpu: 400m
      memory: 2Gi

storage:
  #Create PVC
  create: true
  size: 1000Gi
  className: azurefile

registry:
  - name: conductorcr
    server: conductorcr.azurecr.io
    username: conductorcr
    password: #{REGISTRY_PASSWORD}#

