resources:
  repositories:
    - repository: templates
      type: git
      ref: refs/heads/master
      name: Conductor IaC/Azure Pipeline

trigger: none

variables:
  - group: kubernetes-base
  - group: homologation-kubernetes
  - group: homologation-pier
  - group: google
  - group: hmlg-sandbox
  - group: hmlg-store
  - group: hmlg-cipher
  - group: hmlg-c6bank
  - group: hmlg-neo
  - group: hmlg-visa-direct
  - group: hmlg-sgr
  - group: sandbox-pier
  - group: sandbox-heimdall
  - group: sandbox-cipher
  - group: sandbox-neo
  - group: sandbox-store

stages:
  - template: terraform/pipeline.yaml@templates
    parameters:
      directory: ./terraform/$(CLOUD)/kubernetes/$(PROJECT_NAME)
      jobEnvironment: "$(JOB_ENVIRONMENT)"
      environment: "$(ENVIRONMENT)"
      stateName: "Infrastructure"

  - template: terraform/pipeline.yaml@templates
    parameters:
      directory: ./terraform/application/$(PROJECT_NAME)
      jobEnvironment: "$(JOB_ENVIRONMENT)"
      environment: "$(ENVIRONMENT)"
      stateName: "Application"