replicas: 0
image:  conductorcr.azurecr.io/prepaid/bankslip
version: ${version}
enviroments:
  values: 
    APP_PROFILE: hmle
    CACHE_ENABLED: true
    CACHE_ENTITIES_TENANT: #{BANKSLIP_VNEXT_PROD_CACHE_ENTITIES_TENANT}#
    DATABASE_CONNECTIONURI: #{BANKSLIP_VNEXT_PROD_DATABASE_CONNECTIONURI}#
    DATABASE_MIGRATIONPRINCIPAL_MAXIMUMPOOLSIZE: 2
    DATABASE_MIGRATIONPRINCIPAL_MINIMUMIDLE: 1
    DATABASE_SHOWSQL: false
    DATABASE_TIMEZONE: UTC
    LOG_LEVEL: info
    LOG_SPLUNK: true
    REDIS_DB: 4
    REDIS_URL: #{BANKSLIP_VNEXT_PROD_REDIS_URL}#
    SPLUNK_DIAL: #{BANKSLIP_VNEXT_PROD_SPLUNK_DIAL}#
    SPLUNK_ENABLED: true
    SPLUNK_SKIPTLS: true
    SPLUNK_SOURCE: #{BANKSLIP_VNEXT_PROD_SPLUNK_SOURCE}#
    SPLUNK_TIMEZONE: #{BANKSLIP_VNEXT_PROD_SPLUNK_TIMEZONE}#
    SPLUNK_URL: #{BANKSLIP_VNEXT_PROD_SPLUNK_URL}#
    SWAGGER_IP: #{BANKSLIP_VNEXT_PROD_SWAGGER_IP}#
    SWAGGER_PORT: 80

  secrets:
    DATABASE_PASSWORD: #{BANKSLIP_VNEXT_PROD_DATABASE_PASSWORD}#
    DATABASE_USER: #{BANKSLIP_VNEXT_PROD_DATABASE_USER}#
    REDIS_PASSWORD: #{BANKSLIP_VNEXT_PROD_REDIS_PASSWORD}#
    SPLUNK_TOKEN: #{BANKSLIP_VNEXT_PROD_SPLUNK_TOKEN}#

resources:
  limits:
    cpu: 4
    memory: 512Mi
  requests: 
    cpu: 100m
    memory: 256Mi

registry:
  servers:
    - name: conductorcr
      server: conductorcr.azurecr.io
      username: conductorcr
      password: #{REGISTRY_PASSWORD}#

istio:
  enabled: true 