replicas: 0
image:  conductorcr.azurecr.io/prepaid/exchange
version: ${version}
enviroments:
  values: 
    APP_PROFILE: prod
    CACHE_PREFIX: #{EXCHANGE_VNEXT_PROD_CACHE_PREFIX}#
    CACHE_TYPE: #{EXCHANGE_VNEXT_PROD_CACHE_TYPE}#
    DATABASE_CONNECTIONURI: #{EXCHANGE_VNEXT_PROD_DATABASE_CONNECTIONURI}#
    DATABASE_MIGRATIONPRINCIPAL_MAXIMUMPOOLSIZE: 2
    DATABASE_MIGRATIONPRINCIPAL_MINIMUMIDLE: 1
    DATABASE_SHOWSQL: false
    DATABASE_TIMEZONE: UTC
    LOG_LEVEL: info
    REDIS_DB: 1
    REDIS_URL: #{EXCHANGE_VNEXT_PROD_REDIS_URL}#
    SPLUNK_ENABLED: true
    SPLUNK_SKIPTLS: true
    SPLUNK_SOURCE: #{EXCHANGE_VNEXT_PROD_SPLUNK_SOURCE}#
    SPLUNK_URL: #{EXCHANGE_VNEXT_PROD_SPLUNK_URL}#
    SWAGGER_IP: #{EXCHANGE_VNEXT_PROD_SWAGGER_IP}#
    SWAGGER_PORT: 80
  secrets:
    DATABASE_PASSWORD: #{EXCHANGE_VNEXT_PROD_DATABASE_PASSWORD}#
    DATABASE_USER: #{EXCHANGE_VNEXT_PROD_DATABASE_USER}#
    REDIS_PASSWORD: #{EXCHANGE_VNEXT_PROD_REDIS_PASSWORD}#
    SPLUNK_TOKEN: #{EXCHANGE_VNEXT_PROD_SPLUNK_TOKEN}#

resources:
  limits:
    cpu: 4
    memory: 512Mi
  requests: 
    cpu: 100m
    memory: 256Mi

registry:
  servers:
    - name: conductorcr
      server: conductorcr.azurecr.io
      username: conductorcr
      password: #{REGISTRY_PASSWORD}#

istio:
  enabled: true 