replicas: 0
image:  conductorcr.azurecr.io/pier-cards
version: ${version}
enviroments:
  values: 
    APP_PROFILE: prod
    CACHE_ENABLED: true
    CACHE_ENTITIES_PARAMETERCARD: true
    CACHE_ENTITIES_TENANT: true
    CIPHER_103_426176: 5
    CIPHER_149_509047: 30
    CIPHER_167_650596: 0
    CIPHER_167_651662: 0
    CIPHER_167_655005: 0
    CIPHER_225_417400: 6
    CIPHER_225_417401: 23
    CIPHER_225_417402: 40
    CIPHER_241_536566: 15
    CIPHER_241_550582: 29
    CIPHER_245_509004: 0
    CIPHER_245_509046: 0
    CIPHER_247_655016: 14
    CIPHER_248_467948: 0
    CIPHER_253_655016: 14
    CIPHER_259_487503: 0
    CIPHER_43_509005: 0
    CIPHER_43_509723: 0
    CRONTASK_ENABLE: #{PIERCARDS_VNEXT_PROD_CRONTASK_ENABLE}#
    DATABASE_CONNECTIONURI: #{PIERCARDS_VNEXT_PROD_DATABASE_CONNECTIONURI}#
    DATABASE_KEEPALIVE: 30
    DATABASE_MIGRATIONISSUERS_ENABLED: true
    DATABASE_MIGRATIONISSUERS_MAXIMUMLIFETIME: 25
    DATABASE_MIGRATIONISSUERS_MAXIMUMPOOLSIZE: 2
    DATABASE_MIGRATIONISSUERS_MINIMUMIDLE: 2
    DATABASE_MIGRATIONPRINCIPAL_ENABLED: true
    DATABASE_MIGRATIONPRINCIPAL_MAXIMUMLIFETIME: 25
    DATABASE_MIGRATIONPRINCIPAL_MAXIMUMPOOLSIZE: 2
    DATABASE_MIGRATIONPRINCIPAL_MINIMUMIDLE: 2
    DATABASE_SHOWSQL: false
    DATABASE_TIMEZONE: UTC
    EMBOSSING_ENABLEDENCRYPTION: #{PIERCARDS_VNEXT_PROD_EMBOSSING_ENABLEDENCRYPTION}#
    KAFKA_BROKERS: #{PIERCARDS_VNEXT_PROD_KAFKA_BROKERS}#
    KAFKA_CONNECTIONTIMEOUT: 5s
    KAFKA_ENABLED: true
    KAFKA_PRODUCER_ACK: one
    KAFKA_PRODUCER_WRITETIMEOUT: 5s
    LOG_BILLING_ENABLED: true
    LOG_BILLING_TCP_CONNECTIONSTRING: #{PIERCARDS_VNEXT_PROD_LOG_BILLING_TCP_CONNECTIONSTRING}#
    LOG_BILLING_TCP_ENABLED: true
    LOG_LEVEL: info
    LOG_SPLUNK: true
    RABBIT_DIAL: #{PIERCARDS_VNEXT_PROD_RABBIT_DIAL}#
    RABBIT_VIRTUALHOST: #{PIERCARDS_VNEXT_PROD_RABBIT_VIRTUALHOST}#
    REDIS_CONNECTION: #{PIERCARDS_VNEXT_PROD_REDIS_CONNECTION}#
    SECURITY_AESKEY: #{PIERCARDS_VNEXT_PROD_SECURITY_AESKEY}#
    SERVICEBUS_CARDCDCCONNECTIONSTRING: #{PIERCARDS_VNEXT_PROD_SERVICEBUS_CARDCDCCONNECTIONSTRING}#
    SERVICEBUS_CARDCDCQUEUE: #{PIERCARDS_VNEXT_PROD_SERVICEBUS_CARDCDCQUEUE}#
    SERVICEBUS_CARDCDCSUBSCRIPTION: #{PIERCARDS_VNEXT_PROD_SERVICEBUS_CARDCDCSUBSCRIPTION}#
    SERVICEBUS_CARDCONNECTIONSTRING: #{PIERCARDS_VNEXT_PROD_SERVICEBUS_CARDCONNECTIONSTRING}#
    SERVICEBUS_CARDQUEUE: #{PIERCARDS_VNEXT_PROD_SERVICEBUS_CARDQUEUE}#
    SERVICEBUS_ENABLE: true
    SERVICEBUS_NUMBEROFWORKERS: 10
    SPLUNK_DIAL: #{PIERCARDS_VNEXT_PROD_SPLUNK_DIAL}#
    SPLUNK_TIMEZONE: #{PIERCARDS_VNEXT_PROD_SPLUNK_TIMEZONE}#
    SWAGGER_IP: #{PIERCARDS_VNEXT_PROD_SWAGGER_IP}#
    SWAGGER_PORT: 80
  secrets:
    DATABASE_PASSWORD: #{PIERCARDS_VNEXT_PROD_DATABASE_PASSWORD}#
    DATABASE_USER: #{PIERCARDS_VNEXT_PROD_DATABASE_USER}#

resources:
  limits:
    cpu: 4
    memory: 512Mi
  requests: 
    cpu: 100m
    memory: 256Mi

registry:
  servers:
    - name: conductorcr
      server: conductorcr.azurecr.io
      username: conductorcr
      password: #{REGISTRY_PASSWORD}#

istio:
  enabled: true 