trigger: none

variables:
  - group: kubernetes-base
  - group: production-kubernetes
  - group: production-azure-vnext
  - group: vnext-base
  - group: production-vnext-contabil

stages:
  - template: ../../../../templates/terraform.yaml
    parameters:
      directory: ./terraform/$(CLOUD)/kubernetes/$(PROJECT_NAME)
      jobEnvironment: "$(JOB_ENVIRONMENT)"
      environment: "$(ENVIRONMENT)"
      stateName: "Infrastructure"
