image:  desenvolvimento.azurecr.io/prepaid/installment
version: ${version}
enviroments:
  values: 

    APP_PROFILE: hmlg
    CACHE_ENABLED: true
    CACHE_ENTITIES_TENANT: #{INSTALLMENT_VNEXT_HMLE_CACHE_ENTITIES_TENANT}#
    DATABASE_CONNECTIONURI: #{INSTALLMENT_VNEXT_HMLE_DATABASE_CONNECTIONURI}#
    DATABASE_KEEPALIVE: 60
    DATABASE_POOLISSUERS_CONNMAXLIFETIME: 10
    DATABASE_POOLISSUERS_MAXIDLECONNS: 2
    DATABASE_POOLISSUERS_MAXOPENCONNS: 2
    DATABASE_POOLPRINCIPAL_CONNMAXLIFETIME: 10
    DATABASE_POOLPRINCIPAL_MAXIDLECONNS: 1
    DATABASE_POOLPRINCIPAL_MAXOPENCONNS: 2
    DATABASE_SHOWSQL: false
    DATABASE_TIMEZONE: UTC
    HOST_MSACCOUNT: #{INSTALLMENT_VNEXT_HMLE_HOST_MSACCOUNT}#
    LOG_LEVEL: info
    SERVER_PORT: 8080
    SPLUNK_ENABLED: true
    SPLUNK_SKIPTLS: true
    SPLUNK_SOURCE: #{INSTALLMENT_VNEXT_HMLE_SPLUNK_SOURCE}#
    SPLUNK_URL: #{INSTALLMENT_VNEXT_HMLE_SPLUNK_URL}#
    SWAGGER_IP: #{INSTALLMENT_VNEXT_HMLE_SWAGGER_IP}#
    SWAGGER_PORT: 80

  secrets:

    DATABASE_PASSWORD: #{INSTALLMENT_VNEXT_HMLE_DATABASE_PASSWORD}#
    DATABASE_USER: #{INSTALLMENT_VNEXT_HMLE_DATABASE_USER}#
    PIERTOKEN_1: #{INSTALLMENT_VNEXT_HMLE_PIERTOKEN_1}#
    PIERTOKEN_248: #{INSTALLMENT_VNEXT_HMLE_PIERTOKEN_248}#
    SPLUNK_TOKEN: #{INSTALLMENT_VNEXT_HMLE_SPLUNK_TOKEN}#

resources:
  limits:
    cpu: 4
    memory: 512Mi
  requests: 
    cpu: 100m
    memory: 256Mi

registry:
  servers:
    - name: desenvolvimento
      server: desenvolvimento.azurecr.io
      username: desenvolvimento
      password: #{VNEXT_HMLE_REGISTRY_PASSWORD}#


istio:
  enabled: true 