# This harness-delegate-values.yaml file is compatible with version 1.0.2
# of the harness-delegate helm chart.

# You can download the harness-delegate helm chart at
# https://app.harness.io/storage/harness-download/harness-helm-charts/

# Account Id to which the delegate will be connecting
accountId: ${accountId}

# Secret identifier associated with the account
accountSecret: ${accountSecret}

# Short 6 character identifier of the account
accountIdShort: cdt

delegateName: ${delegateName}

# Id of the delegate profile that needs to run when the delegate is
# coming up
delegateProfile: "${delegateProfile}"

delegateType: "HELM_DELEGATE"

delegateDockerImage: harness/delegate:latest

managerHostAndPort: https://app.harness.io/gratis
watcherStorageUrl: https://app.harness.io/public/free/freemium/watchers
watcherCheckLocation: current.version
remoteWatcherUrlCdn: https://app.harness.io/public/shared/watchers/builds
delegateStorageUrl: https://app.harness.io
delegateCheckLocation: delegatefree.txt
useCdn: true
cdnUrl: https://app.harness.io
jreVersion: 1.8.0_242