image:  desenvolvimento.azurecr.io/prepaid/orchestrator
version: ${version}
enviroments:
  values: 
    APP_PROFILE: hmle
    AZURE_STORAGE_ACCOUNT: #{ORCHESTRATOR_VNEXT_HMLE_AZURE_STORAGE_ACCOUNT}#
    AZURE_STORAGE_CONTAINER: #{ORCHESTRATOR_VNEXT_HMLE_AZURE_STORAGE_CONTAINER}#
    AZURE_STORAGE_KEY: #{ORCHESTRATOR_VNEXT_HMLE_AZURE_STORAGE_KEY}#
    AZURE_STORAGE_URL: #{ORCHESTRATOR_VNEXT_HMLE_AZURE_STORAGE_URL}#
    CACHE_ENABLED: true
    DATABASE_CONNECTIONURI: #{ORCHESTRATOR_VNEXT_HMLE_DATABASE_CONNECTIONURI}#
    DATABASE_KEEPALIVE: 60
    DATABASE_POOLISSUERS_CONNMAXLIFETIME: 10
    DATABASE_POOLISSUERS_MAXIDLECONNS: 2
    DATABASE_POOLISSUERS_MAXOPENCONNS: 2
    DATABASE_POOLPRINCIPAL_CONNMAXLIFETIME: 10
    DATABASE_POOLPRINCIPAL_MAXIDLECONNS: 1
    DATABASE_POOLPRINCIPAL_MAXOPENCONNS: 2
    DATABASE_SHOWSQL: false
    DATABASE_TIMEZONE: UTC
    LOG_LEVEL: #{ORCHESTRATOR_VNEXT_HMLE_LOG_LEVEL}#
    RABBIT_DIAL: #{ORCHESTRATOR_VNEXT_HMLE_RABBIT_DIAL}#
    RABBIT_VIRTUALHOST: #{ORCHESTRATOR_VNEXT_HMLE_RABBIT_VIRTUALHOST}#
    REDIS_DB: 2
    REDIS_TLS: true
    REDIS_URL: #{ORCHESTRATOR_VNEXT_HMLE_REDIS_URL}#
    SPLUNK_ENABLED: true
    SPLUNK_SKIPTLS: true
    SPLUNK_SOURCE: #{ORCHESTRATOR_VNEXT_HMLE_SPLUNK_SOURCE}#
    SPLUNK_URL: #{ORCHESTRATOR_VNEXT_HMLE_SPLUNK_URL}#
    SWAGGER_IP: #{ORCHESTRATOR_VNEXT_HMLE_SWAGGER_IP}#
    SWAGGER_PORT: 80
    URL_ACCOUNT: #{ORCHESTRATOR_VNEXT_HMLE_URL_ACCOUNT}#
    URL_AGGREGATOR: #{ORCHESTRATOR_VNEXT_HMLE_URL_AGGREGATOR}#
    URL_BANKSLIP: #{ORCHESTRATOR_VNEXT_HMLE_URL_BANKSLIP}#
    URL_CONTROL: #{ORCHESTRATOR_VNEXT_HMLE_URL_CONTROL}#
    URL_EXCHANGE: #{ORCHESTRATOR_VNEXT_HMLE_URL_EXCHANGE}#
    URL_OPERATION: #{ORCHESTRATOR_VNEXT_HMLE_URL_OPERATION}#
    URL_PERSON: #{ORCHESTRATOR_VNEXT_HMLE_URL_PERSON}#
    URL_PIERCARDS: #{ORCHESTRATOR_VNEXT_HMLE_URL_PIERCARDS}#
    URL_PRODUCT: #{ORCHESTRATOR_VNEXT_HMLE_URL_PRODUCT}#
    URL_STATEMENT: #{ORCHESTRATOR_VNEXT_HMLE_URL_STATEMENT}#
    URL_TRANSACTION: #{ORCHESTRATOR_VNEXT_HMLE_URL_TRANSACTION}#

  secrets:
    DATABASE_PASSWORD: #{ORCHESTRATOR_VNEXT_HMLE_DATABASE_PASSWORD}#
    DATABASE_USER: #{ORCHESTRATOR_VNEXT_HMLE_DATABASE_USER}#
    REDIS_PASSWORD: #{ORCHESTRATOR_VNEXT_HMLE_REDIS_PASSWORD}#
    SPLUNK_TOKEN: #{ORCHESTRATOR_VNEXT_HMLE_SPLUNK_TOKEN}#

resources:
  limits:
    cpu: 4
    memory: 512Mi
  requests: 
    cpu: 100m
    memory: 256Mi

registry:
  servers:
    - name: desenvolvimento
      server: desenvolvimento.azurecr.io
      username: desenvolvimento
      password: #{VNEXT_HMLE_REGISTRY_PASSWORD}#


istio:
  enabled: true 