replicas: 0
image:  conductorcr.azurecr.io/vnext/vhub
version: ${version}
enviroments:
  values: 
    ACCOUNT_URL: #{VHUB_VNEXT_PROD_ACCOUNT_URL}# 
    APP_PROFILE: hmle
    BILLING_URL: #{VHUB_VNEXT_PROD_BILLING_URL}# 
    DATABASE_CONNECTIONURI: #{VHUB_VNEXT_PROD_DATABASE_CONNECTIONURI}#
    DATABASE_KEEPALIVE: "60"
    DATABASE_PCHPOOLISSUERS_CONNMAXLIFETIME: "10"
    DATABASE_PCHPOOLISSUERS_MAXIDLECONNS: "2"
    DATABASE_PCHPOOLISSUERS_MAXOPENCONNS: "2"
    DATABASE_POOLISSUERS_CONNMAXLIFETIME: "10"
    DATABASE_POOLISSUERS_MAXIDLECONNS: "2"
    DATABASE_POOLISSUERS_MAXOPENCONNS: "2"
    DATABASE_POOLPRINCIPAL_CONNMAXLIFETIME: "10"
    DATABASE_POOLPRINCIPAL_MAXIDLECONNS: "1"
    DATABASE_POOLPRINCIPAL_MAXOPENCONNS: "2"
    DATABASE_SHOWSQL: "false"
    KAFKA_BROKERS: #{VHUB_VNEXT_PROD_KAFKA_BROKERS}#
    KAFKA_CONSUMER_GROUPID: vhub
    KAFKA_CONSUMER_OFFSETAUTOCOMMIT: "false"
    KAFKA_CONSUMER_OFFSETTYPE: earliest
    KAFKA_CONSUMER_RETRY_DURATIONS: 1s 1s 3s 5s 1m
    KAFKA_CONSUMER_RETRY_POOLSIZE: "50"
    KAFKA_PRODUCER_ACK: one
    LOG_LEVEL: info
    ORCHESTRATOR_URL: #{VHUB_VNEXT_PROD_ORCHESTRATOR_URL}# 
    SPLUNK_ENABLED: "true"
    SPLUNK_SKIPTLS: "true"
    SPLUNK_SOURCE: vhub
    SPLUNK_URL: #{VHUB_VNEXT_PROD_SPLUNK_URL}# 
    STATEMENT_URL: #{VHUB_VNEXT_PROD_STATEMENT_URL}# 
  secrets:
    DATABASE_PASSWORD: #{VHUB_VNEXT_PROD_DATABASE_PASSWORD}# 
    DATABASE_USER: #{VHUB_VNEXT_PROD_DATABASE_USER}# 
    SPLUNK_TOKEN: #{VHUB_VNEXT_PROD_SPLUNK_TOKEN}# 


resources:
  limits:
    cpu: 4
    memory: 512Mi
  requests: 
    cpu: 100m
    memory: 256Mi

registry:
  servers:
    - name: conductorcr
      server: conductorcr.azurecr.io
      username: conductorcr
      password: #{REGISTRY_PASSWORD}#

istio:
  enabled: true 