image:  desenvolvimento.azurecr.io/vnext/statement
version: ${version}
enviroments:
  values: 

    APP_PROFILE: hmle
    CACHE_ENABLED: true
    CACHE_ENTITIES_TENANT: #{STATEMENT_VNEXT_HMLE_CACHE_ENTITIES_TENANT}#
    DATABASE_CONNECTIONURI: #{STATEMENT_VNEXT_HMLE_DATABASE_CONNECTIONURI}#
    DATABASE_POOLISSUERS_CONNMAXLIFETIME: 10
    DATABASE_POOLISSUERS_MAXIDLECONNS: 1
    DATABASE_POOLISSUERS_MAXOPENCONNS: 2
    DATABASE_POOLPRINCIPAL_CONNMAXLIFETIME: 10
    DATABASE_POOLPRINCIPAL_MAXIDLECONNS: 1
    DATABASE_POOLPRINCIPAL_MAXOPENCONNS: 2
    DATABASE_SHOWSQL: false
    DATABASE_TIMEZONE: UTC
    LOG_LEVEL: info
    REDIS_DB: 3
    REDIS_TLS: true
    REDIS_URL: #{STATEMENT_VNEXT_HMLE_REDIS_URL}#
    SPLUNK_ENABLED: True
    SPLUNK_SKIPTLS: True
    SPLUNK_URL: #{STATEMENT_VNEXT_HMLE_SPLUNK_URL}#
    SWAGGER_IP: #{STATEMENT_VNEXT_HMLE_SWAGGER_IP}#
    SWAGGER_PORT: 80

  secrets:

    DATABASE_PASSWORD: #{STATEMENT_VNEXT_HMLE_DATABASE_PASSWORD}#
    DATABASE_USER: #{STATEMENT_VNEXT_HMLE_DATABASE_USER}#
    REDIS_PASSWORD: #{STATEMENT_VNEXT_HMLE_REDIS_PASSWORD}#

resources:
  limits:
    cpu: 4
    memory: 512Mi
  requests: 
    cpu: 100m
    memory: 256Mi

registry:
  servers:
    - name: desenvolvimento
      server: desenvolvimento.azurecr.io
      username: desenvolvimento
      password: #{VNEXT_HMLE_REGISTRY_PASSWORD}#


istio:
  enabled: true 