trigger: none

variables:
  - group: kubernetes-base
  - group: production-azure
  - group: production-kubernetes
  - group: csp-odin-1

stages:
  - template: ../../../../templates/terraform.yaml
    parameters:
      directory: ./terraform/$(CLOUD)/kubernetes/$(PROJECT_NAME)
      jobEnvironment: "$(JOB_ENVIRONMENT)"
      environment: "$(ENVIRONMENT)"
      stateName: "Infrastructure"
  
  - template: ../../../../templates/terraform.yaml
    parameters:
      directory: ./terraform/application/$(PROJECT_NAME)
      jobEnvironment: "$(JOB_ENVIRONMENT)"
      environment: "$(ENVIRONMENT)"
      stateName: "Application"