replicas: 0
image:  conductorcr.azurecr.io/prepaid/aggregator
version: ${version}
enviroments:
  values: 
    APP_NAME: aggregator
    APP_PROFILE: hmlg
    CACHE_ENABLED: true
    CACHE_ENTITIES_TENANT: false
    DATABASE_ADDRESS: #{AGGREGATOR_VNEXT_PROD_DATABASE_ADDRESS}#
    DATABASE_DATABASE: #{AGGREGATOR_VNEXT_PROD_DATABASE_DATABASE}#
    DATABASE_MAXCONNAGE: 25m
    DATABASE_MIGRATIONPRINCIPAL_MAXIMUMPOOLSIZE: 2
    DATABASE_MIGRATIONPRINCIPAL_MINIMUMIDLE: 2
    KAFKA_BROKERS: 10.70.64.181:9094
    KAFKA_CONNECTIONTIMEOUT: 5
    KAFKA_ENABLED: true
    KAFKA_PRODUCER_ACK: one
    KAFKA_PRODUCER_WRITETIMEOUT: 5
    LOG_LEVEL: info
    SPLUNK_ENABLED: true
    SPLUNK_SKIPTLS: true
    SPLUNK_SOURCE: aggregator
    SPLUNK_URL: #{AGGREGATOR_VNEXT_PROD_SPLUNK_URL}#
    SWAGGER_IP: #{AGGREGATOR_VNEXT_PROD_SWAGGER_IP}#
    SWAGGER_PORT: 80
  secrets:
    DATABASE_PASSWORD: #{AGGREGATOR_VNEXT_PROD_DATABASE_PASSWORD}#
    DATABASE_USER: #{AGGREGATOR_VNEXT_PROD_DATABASE_USER}#
    SPLUNK_TOKEN: #{AGGREGATOR_VNEXT_PROD_SPLUNK_TOKEN}#

resources:
  limits:
    cpu: 4
    memory: 512Mi
  requests: 
    cpu: 100m
    memory: 256Mi

registry:
  servers:
    - name: conductorcr
      server: conductorcr.azurecr.io
      username: conductorcr
      password: #{REGISTRY_PASSWORD}#

istio:
  enabled: true 