service:
  annotations: 
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  type: LoadBalancer

monitor: 
  prometheusRule:
    default: 
      additionalRuleLabels: 
        cloud: azure
        cluster: ${cluster_name}  