replicas: 1
image: "conductorcr.azurecr.io/pierlabs-hmlg/pier-api"
version: "2.214.0"

autoScale:
  maxReplicas: 5
  
registry:
  - name: conductorcr
    server: conductorcr.azurecr.io
    username: conductorcr
    password: #{REGISTRY_PASSWORD}#

service:
  type: LoadBalancer
  port: 8181
  annotations:
    cloud.google.com/load-balancer-type: Internal
    networking.gke.io/internal-load-balancer-allow-global-access: "true"  

enviroments:
  # non sensitive variables
  values:
    LOGGING_LEVEL_BR_COM_CONDUCTOR: "INFO"
    MANAGEMENT_HEALTH_MAIL_ENABLED: "false"
    PIER_ENCRYPT_ENABLED: "true"
    PIER_RABBIT_HOST: "rabbitmq.rabbitmq-default"
    PIER_RABBIT_PORT: "5672"
    PIER_REDIS_PORT: "6379"
    PIER_WSDL_PORTALWS: "http://10.8.3.65:25781/Portal_WS.asmx?wsdl"
    SPRING_PROFILES_ACTIVE: "hmlg"
    TZ: "America/Recife"
    PIER_SPLUNK_LOGS_ENABLED: "true"
    PIER_SPLUNK_LOGS_HOST: 10.70.30.11
    PIER_SPLUNK_LOGS_PORT: "9090"
    
redis:
  enabled: true
  name: "redis"
  namespace:
    create: true

rabbitmq:
  enabled: false