enviroments:
  # non sensitive variables
  values:
    DD_JMXFETCH_ENABLED: "true"
    DD_TRACE_AGENT_PORT: "8126"
    DD_TRACE_ANALYTICS_ENABLED: "true"
    DD_AGENT_HOST: "10.75.143.200"
    PIER_DATASOURCE_EXECUTELIQUIBASE: "false"
    PIER_AUTORIZADOR_IP: "10.75.33.164"
    PIER_RABBIT_VIRTUALHOST: pier-hmlgi-hp-candidate
    SPRING_JPA_SHOW_SQL: "false"
    SPRING_PROPERTIES_HIBERNATE_FORMAT_SQL: "false"
  secrets:
    PIER_DATASOURCE_PIER_SERVERNAME: #{HP_CANDIDATE_PIER_DATASOURCE_PIER_SERVERNAME}#
    PIER_DATASOURCE_PIER_USERNAME: #{HP_CANDIDATE_PIER_DATASOURCE_PIER_USERNAME}#
    PIER_DATASOURCE_PIER_PASSWORD: #{HP_CANDIDATE_PIER_DATASOURCE_PIER_PASSWORD}#