enviroments:
  values:
    PIER_RABBIT_VIRTUALHOST: pier-hmlgi-iris
    PIER_DATASOURCE_PIER_DATABASENAME: "PIER_V2"
  secrets:
    PIER_DATASOURCE_PIER_SERVERNAME: #{IRIS_PIER_DATASOURCE_PIER_SERVERNAME}#
    PIER_DATASOURCE_PIER_USERNAME: #{IRIS_PIER_DATASOURCE_PIER_USERNAME}#
    PIER_DATASOURCE_PIER_PASSWORD: #{IRIS_PIER_DATASOURCE_PIER_PASSWORD}#