enviroments:
  # non sensitive variables
  values:
    PIER_RABBIT_VIRTUALHOST: "pb-pier"
    PIER_REDIS_HOST: "redis.pb-pier-redis"
    PIER_AUTORIZADOR_IP: "10.60.33.35"
    PIER_CACHEENABLE: "true"
    PIER_CIPHER_PATH: "http://10.75.30.90:8080"
    PIER_DATASOURCE_CEP_SERVERNAME: "10.75.33.40"
    PIER_DATASOURCE_EXECUTELIQUIBASE: "true"
    PIER_DATASOURCE_PIER_DATABASENAME: "PIER_HMLG_V2"
    PIER_DATASOURCE_QUARTZ_DATASOURCEURL: "jdbc:sqlserver://10.75.33.40:1433;databaseName=PIER_HMLG_V2;appName=PIER_QUARTZ"
    PIER_JOB_EXECUTEJOB: "false" 
    PIER_REGISTROONLINE_CACERTS: "/usr/local/openjdk-15/lib/security/cacerts"
    PIER_TRACE_PRINTALLTRACE: "true"
    SERVER_PORT: "8181"
    SPRING_JPA_SHOW_SQL: "false"
    SWAGGER_PROTOCOL: "https"
    PIER_SPLUNK_LOGS_ENABLED: "true"
    PIER_SPLUNK_LOGS_HOST: 10.70.30.11
    PIER_SPLUNK_LOGS_PORT: "9090"

  secrets:
    PIER_DATASOURCE_PIER_SERVERNAME: #{PB_PIER_DATASOURCE_PIER_SERVERNAME}#
    PIER_DATASOURCE_PIER_USERNAME: #{PB_PIER_DATASOURCE_PIER_USERNAME}#
    PIER_DATASOURCE_PIER_PASSWORD: #{PB_PIER_DATASOURCE_PIER_PASSWORD}#
    PIER_DATASOURCE_QUARTZ_DATASOURCEPASSWORD: #{PB_PIER_DATASOURCE_PIER_PASSWORD}#
