api:
  enviroments:
    values:
      SPRING_RABBITMQ_VIRTUAL-HOST: "hp-heimdall"
      HEIMDALL_REDIS_HOST: "redis.hp-heimdall-redis"
      HEIMDALL_DATASOURCE_DATABASENAME: "Heimdall"
      HEIMDALL_MONGO_ENABLED: "true"
      HEIMDALL_MONGO_PORT: "27017"
      HEIMDALL_MONGO_SERVERNAME: "mongo"
      HEIMDALL_MONGO_URL: "mongodb://az2e-heimdall-condom:XADS8WMWQQ9tMZ761oRfphZs3jDSc7wuis5HuZF6GJCoBXgPgvctUbyw5AfZnyAUQ3ABpGJ0QDZZBkMJLlovyg==@az2e-heimdall-condom.documents.azure.com:10255/?ssl=true&replicaSet=globaldb"
      SPRING_JPA_HIBERNATE_NAMING-STRATEGY: "org.hibernate.cfg.EJB3NamingStrategy"
          
    secrets:
      HEIMDALL_DATASOURCE_SERVERNAME: #{HP_HEIMDALL_DATASOURCE_SERVERNAME}#
      HEIMDALL_DATASOURCE_USERNAME: #{HP_HEIMDALL_DATASOURCE_USERNAME}#
      HEIMDALL_DATASOURCE_PASSWORD: #{HP_HEIMDALL_DATASOURCE_PASSWORD}#
   
gateway:
  enviroments:
    values:
      SPRING_RABBITMQ_VIRTUAL-HOST: "hp-heimdall"
      HEIMDALL_REDIS_HOST: "redis.hp-heimdall-redis"
      HEIMDALL_DATASOURCE_DATABASENAME: "Heimdall"
      HEIMDALL_MONGO_ENABLED: "false"
      SPRING_JPA_HIBERNATE_NAMING-STRATEGY: "org.hibernate.cfg.EJB3NamingStrategy"
 
    secrets:
      HEIMDALL_DATASOURCE_SERVERNAME: #{HP_HEIMDALL_DATASOURCE_SERVERNAME}#
      HEIMDALL_DATASOURCE_USERNAME: #{HP_HEIMDALL_DATASOURCE_USERNAME}#
      HEIMDALL_DATASOURCE_PASSWORD: #{HP_HEIMDALL_DATASOURCE_PASSWORD}#
   
  ingress:
    enabled: true  

    annotations: 
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/service-upstream: "true"
      
    hosts:
      - url: "heimdall-hp-hmlext.devcdt.com.br"
        path: /*
        pathType: ImplementationSpecific
    
    tls:
      enabled: false
      hosts:
        - url: "heimdall-hp-hmlext.devcdt.com.br"
