api:
  replicas: 1
  image: ${api_image}
  version: ${api_version}

  enviroments:
    # non sensitive variables
    values:
      HEIMDALL_DATASOURCE_DATABASENAME: "Heimdall"
      HEIMDALL_DATASOURCE_DATASOURCECLASSNAME: "com.microsoft.sqlserver.jdbc.SQLServerDataSource"
      HEIMDALL_DATASOURCE_PORTNUMBER: "1433"
      HEIMDALL_MIDDLEWARE_DELETEDEPRECATED: "true"
      HEIMDALL_REDIS_HOST: "redis.redis-default"
      HEIMDAL_REDIS_PORT: "6379"
      SERVER_PORT: "9090"
      SPRING_DATASOURCE_DATABASETYPE: "SQLServer"
      SPRING_JPA_DATABASE: "SQL_SERVER"
      SPRING_JPA_DATABASE-PLATFORM: "org.hibernate.dialect.SQLServer2012Dialect"
      SPRING_PROFILES_ACTIVE: "hmlg"
      SPRING_RABBITMQ_HOST: "rabbitmq.rabbitmq-default"
      SPRING_RABBITMQ_PORT: "5672"

  service:
    type: LoadBalancer
    ports:
      - name: 9090tcp
        targetPort: 9090
    labels:
      app: heimdall-api

frontend:
  replicas: 1
  image: ${frontend_image}
  version: ${frontend_version}

  enviroments:
    # non sensitive variables
    values:
      REACT_APP_API: "/v1/api"
      REACT_APP_PORT: "9090"
      REACT_APP_SCHEME: "HTTP"
      REACT_APP_VERSION: "1.3.0"
  
  service:
    type: LoadBalancer
    ports:
      - name: 5000tcp
        targetPort: 5000
    labels:
      app: heimdall-frontend
      
gateway:
  replicas: 1
  image: ${gateway_image}

  enviroments:
    # non sensitive variables
    values:
      HEIMDALL_DATASOURCE_DATASOURCECLASSNAME: "com.microsoft.sqlserver.jdbc.SQLServerDataSource"
      HEIMDALL_DATASOURCE_PORTNUMBER: "1433"
      HEIMDALL_REDIS_HOST: "redis.redis-default"
      HEIMDALL_REDIS_PORT: "6379"
      SERVER_PORT: "8080"
      SPRING_DATASOURCE_DATABASETYPE: "SQLServer"
      SPRING_JPA_DATABASE: "SQL_SERVER"
      SPRING_JPA_DATABASE-PLATFORM: "org.hibernate.dialect.SQLServer2012Dialect"
      SPRING_PROFILES_ACTIVE: "hmlg"
      SPRING_RABBITMQ_HOST: "rabbitmq.rabbitmq-default"
      SPRING_RABBITMQ_PORT: "5672"

  autoScale:
    enabled: true 
    minReplicas: 1
    maxReplicas: 3

  service:
    type: LoadBalancer
    ports:
      - name: 8080tcp
        targetPort: 8080
        
registry:
  - name: conductorcr
    server: conductorcr.azurecr.io
    username: conductorcr
    password: #{REGISTRY_PASSWORD}#

redis:
  enabled: false

rabbitmq:
  enabled: false
