api:
  enviroments:
    # non sensitive variables
    values:
      HEIMDALL_TRACE_PRINTALLTRACE: "false"
      SPRING_JPA_SHOW_SQL: "false"
      ZUUL_FILTER_ROOT: "/tmp/interceptores"
      SPRING_RABBITMQ_VIRTUAL-HOST: "heimdall-hmlgi-iris"


    secrets:
      HEIMDALL_DATASOURCE_SERVERNAME: #{IRIS_HEIMDALL_DATASOURCE_SERVERNAME}#
      HEIMDALL_DATASOURCE_USERNAME: #{IRIS_HEIMDALL_DATASOURCE_USERNAME}#
      HEIMDALL_DATASOURCE_PASSWORD: #{IRIS_HEIMDALL_DATASOURCE_PASSWORD}#
   
gateway:

  enviroments:
    # non sensitive variables
    values:
      HEIMDALL_DATASOURCE_DATABASENAME: "Heimdall"
      HEIMDALL_TRACE_PRINTALLTRACE: "false"
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_RABBITMQ_VIRTUAL-HOST: "heimdall-hmlgi-iris"

    secrets:
      HEIMDALL_DATASOURCE_SERVERNAME: #{IRIS_HEIMDALL_DATASOURCE_SERVERNAME}#
      HEIMDALL_DATASOURCE_USERNAME: #{IRIS_HEIMDALL_DATASOURCE_USERNAME}#
      HEIMDALL_DATASOURCE_PASSWORD: #{IRIS_HEIMDALL_DATASOURCE_PASSWORD}#
