api:
  service:
    annotations: 
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"

frontend:
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"

rabbitmq:
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"