replicas: 0
image:  conductorcr.azurecr.io/prepaid/product
version: ${version}
enviroments:
  values: 
    APP_PROFILE: prod
    CACHE_ENABLED: true
    CACHE_ENTITIES_TENANT: #{PRODUCT_VNEXT_PROD_CACHE_ENTITIES_TENANT}#
    DATABASE_CONNECTIONURI: #{PRODUCT_VNEXT_PROD_DATABASE_CONNECTIONURI}#
    DATABASE_MIGRATIONPRINCIPAL_MAXIMUMPOOLSIZE: 2
    DATABASE_MIGRATIONPRINCIPAL_MINIMUMIDLE: 1
    DATABASE_SHOWSQL: false
    DATABASE_TIMEZONE: UTC
    LOG_LEVEL: info
    SPLUNK_ENABLED: true
    SPLUNK_SKIPTLS: true
    SPLUNK_SOURCE: #{PRODUCT_VNEXT_PROD_SPLUNK_SOURCE}#
    SPLUNK_URL: #{PRODUCT_VNEXT_PROD_SPLUNK_URL}#
    SWAGGER_IP: #{PRODUCT_VNEXT_PROD_SWAGGER_IP}#
    SWAGGER_PORT: 80
  secrets:
    DATABASE_PASSWORD: #{PRODUCT_VNEXT_PROD_DATABASE_PASSWORD}#
    DATABASE_USER: #{PRODUCT_VNEXT_PROD_DATABASE_USER}#
    SPLUNK_TOKEN: #{PRODUCT_VNEXT_PROD_SPLUNK_TOKEN}#

resources:
  limits:
    cpu: 4
    memory: 512Mi
  requests: 
    cpu: 100m
    memory: 256Mi

registry:
  servers:
    - name: conductorcr
      server: conductorcr.azurecr.io
      username: conductorcr
      password: #{REGISTRY_PASSWORD}#

istio:
  enabled: true 