resources:
  repositories:
    - repository: templates
      type: git
      ref: refs/heads/master
      name: Conductor IaC/Azure Pipeline

trigger: none

variables:
  
  # Common:
  - group: kubernetes-base
  - group: non-prod-azure
  - group: non-prod-rancher

  # Specific:  
  - group: qa-pierflex-general
  - group: harness
  
stages:
  
  # K8S CLUSTER:
  - template: terraform/pipeline.yaml@templates
    parameters:
      directory: ./terraform/azure/$(PROJECT_NAME)
      jobEnvironment: "$(JOB_ENVIRONMENT)"
      environment: "$(ENVIRONMENT)"
      stateName: "Infrastructure"
      azureSubscription: "Conductor QA IaC"
  
  # APPLICATIONS:
  - template: terraform/pipeline.yaml@templates
    parameters:
     directory: ./terraform/application/$(PROJECT_NAME)
     jobEnvironment: "$(JOB_ENVIRONMENT)"
     environment: "$(ENVIRONMENT)"
     stateName: "Application"
     azureSubscription: "Conductor QA IaC"