controller:
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"

    internal:
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
