replicas: 0
image:  conductorcr.azurecr.io/datahub/api
version: ${version}
enviroments:
  values: 
    APP_PROFILE: production
    BLOBSTORAGE_AZURE_ACCOUNT: #{DATAHUB_MASTER_VNEXT_PROD_BLOBSTORAGE_AZURE_ACCOUNT}# 
    BLOBSTORAGE_UPLOADOPTIONS_BLOCKSIZEMB: "4"
    BLOBSTORAGE_UPLOADOPTIONS_PARALLELISM: "4"
    CACHE_ENABLED: "true"
    CACHE_REDIS_DB: "14"
    DATABASE_CONNECTIONPOOL_MAXIMUMPOOLSIZE: "1"
    DATABASE_CONNECTIONPOOL_MINIMUMIDLE: "1"
    DATABASE_SHOWSQL: "false"
    DATAHUB_DEFAULTFILTERCOLUMN: updated_at
    DATAHUB_FILECREATION_MAXRECORDSPERFILE: "20000"
    DATAHUB_FILECREATION_SOURCEDIRECTORY: /files/datahub
    DATAHUB_GRAPHQL_QUERY_COMPLEXITY: "38"
    DATAHUB_GRAPHQL_QUERY_LIMIT: "1"
    DATAHUB_ISSUERRATELIMITING_LIMITPERQUERYASYNC: "5000000"
    DATAHUB_ISSUERRATELIMITING_LIMITPERQUERYSYNC: "10000"
    DATAHUB_ISSUERRATELIMITING_MAXPENDINGFILES: "5"
    DATAHUB_KAFKA_CONSUMERGROUPID: datahub
    DATAHUB_KAFKA_TOPICS_FILESMERGE: #{DATAHUB_MASTER_VNEXT_PROD_DATAHUB_KAFKA_TOPICS_FILESMERGE}# 
    DATAHUB_KAFKA_TOPICS_FILESPARTITIONS: #{DATAHUB_MASTER_VNEXT_PROD_DATAHUB_DATAHUB_KAFKA_TOPICS_FILESPARTITIONS}#  
    DATAHUB_KAFKA_TOPICS_FILESPARTITIONSCOMPLETED: #{DATAHUB_MASTER_VNEXT_PROD_DATAHUB_KAFKA_TOPICS_FILESPARTITIONSCOMPLETED}# 
    DATAHUB_KAFKA_TOPICS_FILESREQUEST: #{DATAHUB_MASTER_VNEXT_PROD_DATAHUB_KAFKA_TOPICS_FILESREQUEST}# 
    DATAHUB_LOG_OUTPUT: splunk
    DATAHUB_USESQLASDEFAULT: "true"
    DRUID_HTTP_URL: #{DATAHUB_MASTER_VNEXT_PROD_DRUID_HTTP_URL}#
    KAFKA_BROKERS: #{DATAHUB_MASTER_VNEXT_PROD_KAFKA_BROKERS}# 
    KAFKA_CONSUMER_HEARTBEATINTERVALSEC: "5"
    KAFKA_CONSUMER_MAXPROCESSINGTIMESEC: "600"
    KAFKA_CONSUMER_MAXWAITSECONS: "10"
    KAFKA_CONSUMER_SESSIONTIMEOUTSEC: "20"
    KAFKA_PRODUCER_BATCHSIZE: "1"
    KAFKA_PRODUCER_BATCHTIMEOUTMILLIS: "0"
    KAFKA_PRODUCER_RETRYBACKOFFSEC: "6"
    KAFKA_PRODUCER_RETRYMAX: "5"
    KAFKA_PRODUCER_RETURNSUCESSES: "true"
    LOG_LEVEL: info
    SPLUNK_ENABLED: "true"
    SPLUNK_HOST: #{DATAHUB_MASTER_VNEXT_PROD_SPLUNK_HOST}# 
    SPLUNK_SOURCE: datahub-api
    TOKEN_SECRET: ""
  secrets:
    BLOBSTORAGE_AZURE_ACCESSKEY: #{DATAHUB_MASTER_VNEXT_PROD_BLOBSTORAGE_AZURE_ACCESSKEY}#
    APP_HOST: #{DATAHUB_MASTER_VNEXT_PROD_APP_HOST}#
    CACHE_REDIS_ADDR: #{DATAHUB_MASTER_VNEXT_PROD_CACHE_REDIS_ADDR}#
    CACHE_REDIS_PASSWORD: #{DATAHUB_MASTER_VNEXT_PROD_CACHE_REDIS_PASSWORD}#
    DATABASE_CONNECTIONURI: #{DATAHUB_MASTER_VNEXT_PROD_DATABASE_CONNECTIONURI}#
    DATABASE_PASSWORD: #{DATAHUB_MASTER_VNEXT_PROD_DATABASE_PASSWORD}#
    DATABASE_USER: #{DATAHUB_MASTER_VNEXT_PROD_DATABASE_USER}#
    DATAHUB_AUTHENTICATION_TOKEN_MASTER: #{DATAHUB_MASTER_VNEXT_PROD_AUTHENTICATION_TOKEN_MASTER}#
    SPLUNK_TOKEN: #{DATAHUB_MASTER_VNEXT_PROD_SPLUNK_TOKEN}#


resources:
  limits:
    cpu: 4
    memory: 512Mi
  requests: 
    cpu: 100m
    memory: 256Mi

registry:
  servers:
    - name: conductorcr
      server: conductorcr.azurecr.io
      username: conductorcr
      password: #{REGISTRY_PASSWORD}#

istio:
  enabled: true 