externalUrl: https://rundeck.devcdt.com.br

ingress:
  hosts:
     - url: rundeck.devcdt.com.br

  tls:
    hosts:
      - url: rundeck.devcdt.com.br

executionStorage:
  azure:
    storageAccount: cdtrundeckstorage

ldap:
  server: conductor.tecnologia
  bindDN: CN=srv.rundeckdev,OU=Rundeck,OU=Applications,DC=conductor,DC=tecnologia
  user:
    bindDN: DC=conductor,DC=tecnologia
  role:
    bindDN: OU=Rundeck,OU=Applications,DC=conductor,DC=tecnologia

acls:
  - name: ad-admin.aclpolicy
    value: |
      description: Admin, all access.
      context:
        project: '.*' # all projects
      for:
        resource:
          - allow: '*' # allow read/create all kinds
        adhoc:
          - allow: '*' # allow read/running/killing adhoc jobs
        job:
          - allow: '*' # allow read/write/delete/run/kill of all jobs
        node:
          - allow: '*' # allow read/run for all nodes
      by:
        group: G_Admin_Rundeck_Dev
      ---
      description: Admin, all access.
      context:
        application: 'rundeck'
      for:
        resource:
          - allow: '*' # allow create of projects
        project:
          - allow: '*' # allow view/admin of all projects
        project_acl:
          - allow: '*' # allow admin of all project-level ACL policies
        storage:
          - allow: '*' # allow read/create/update/delete for all /keys/* storage content
      by:
        group: G_Admin_Rundeck_Dev
  - name: ad-readonly.aclpolicy
    value: |
      description: ReadOnly Access
      context:
        project: '.*' # all projects
      for:
        resource:
          - allow: [read] # allow read all kinds
        adhoc:
          - allow: [read] # allow read adhoc jobs
        job:
          - allow: [read] # allow read of all jobs
        node:
          - allow: [read] # allow read for all nodes
      by:
        group: G_User_Rundeck_Dev
      ---
      description: ReadOnly Access
      context:
        application: 'rundeck'
      for:
        resource:
          - equals:
              kind: system
            allow: [read] # allow read of system info
        project:
          - allow: [read] # allow view of all projects
        storage:
          - allow: [read] # allow read for all /keys/* storage content
      by:
        group: G_User_Rundeck_Dev
  - name: ad-readonly-run.aclpolicy
    value: |
      description: ReadOnly and Run Access
      context:
        project: '.*' # all projects
      for:
        resource:
          - allow: [read] # allow read all kinds
        adhoc:
          - allow: [read, run] # allow read adhoc jobs
        job:
          - allow: [read, view, run] # allow read of all jobs
        node:
          - allow: [read, run] # allow read for all nodes
      by:
        group: G_Run_Rundeck_Dev
      ---
      description: ReadOnly Access
      context:
        application: 'rundeck'
      for:
        resource:
          - equals:
              kind: system
            allow: [read] # allow read of system info
        project:
          - allow: [read] # allow view of all projects
        storage:
          - allow: [read] # allow read for all /keys/* storage content
      by:
        group: G_Run_Rundeck_Dev
  - name: ad-project-admin.aclpolicy
    value: |
      description: Admin Project Access
      context:
        project: '.*' # all projects
      for:
        resource:
          - allow: '*' # allow read all kinds
        adhoc:
          - allow: '*' # allow read adhoc jobs
        job:
          - allow: '*' # allow read of all jobs
        node:
          - allow: '*' # allow read for all nodes
      by:
        group: G_Admin_Project_Rundeck_Dev
      ---
      description: Admin Project Access
      context:
        application: 'rundeck'
      for:
        resource:
          - equals:
              kind: system
            allow: [read] # allow read of system info
        project:
          - allow: [create] # allow view of all projects
        storage:
          - allow: [read,create] # allow read for all /keys/* storage content
      by:
        group: G_Admin_Project_Rundeck_Dev         

postgres:
  storage:
    size: 30Gi               